### ISSUE TITLE
Add docs link

### ISSUE THREAD

**Issue by moshloop** [flanksource/website-issues#1]
Add Docs link in navbar and footer - [docs.flanksource.com](http://docs.flanksource.com/)  bu moving Blog under Resources dropdown

**Comment by leonardosusnja** [comment]
https://flanksource.webflow.io/ Added

**Comment by moshloop** [comment]
@leonardosusnja this link should be added on all the footers

**Comment by leonardosusnja** [comment]
There are already Docs and Blog in the footer.
